controller_manager:
  ros__parameters:
    update_rate: 250

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    ur5e_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    forward_position_controller:
      type: position_controllers/JointGroupPositionController

    gripper_position_controller:
      type: position_controllers/GripperActionController

ur5e_arm_controller:
  ros__parameters:
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 50.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false

forward_position_controller:
  ros__parameters:
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint

gripper_position_controller:
  ros__parameters:
    action_monitor_rate: 20.0
    allow_stalling: true
    goal_tolerance: 0.01
    joint: 'robotiq_85_left_knuckle_joint'
    max_effort: 100.0
    stall_timeout: 3.0
    stall_velocity_threshold: 0.001
